version: '3.8'

services:
  db:
    image: postgres:18.3-trixie
    container_name: microcourse-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qxnzy_microcourse
    volumes:
      - pgdata:/var/lib/postgresql/data
      # 挂载建表脚本，第一次启动时自动初始化表格
      - ./init-sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U micro_user -d qxnzy_microcourse"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./qxnzy-microcourse-backend
    container_name: microcourse-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy # 确保数据库不仅启动了，而且准备就绪了
    environment:
      - DATABASE_URL=postgres://micro_user:micro_password@db:5432/qxnzy_microcourse
      #- ALIYUN_OSS_ACCESS_KEY_ID=your_ak
      #- ALIYUN_OSS_ACCESS_KEY_SECRET=your_sk

  frontend:
    build:
      context: ./qxnzy-microcourse-frontend
    container_name: microcourse-frontend
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=/api
    depends_on:
      - backend

  nginx:
    image: nginx:1.28.3-alpine3.23
    container_name: microcourse-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend

volumes:
  pgdata: